import { fileURLToPath } from "node:url";

const fromProjectRoot = (relativePath: string): string =>
  fileURLToPath(new URL(`../${relativePath}`, import.meta.url));

export const paths = {
  accrualEntries: fromProjectRoot("data/accrual_entries.json"),
  newTransactions: fromProjectRoot("data/new_transactions.json"),
  matchesOutput: fromProjectRoot("result/matches_output.json"),
} as const;

export const matchingConfig = {
  weights: {
    vendor: 0.3,
    amount: 0.35,
    memo: 0.15,
    date: 0.12,
    glAccount: 0.08,
  },
  thresholds: {
    candidateFloor: 0.25,
    accepted: 0.65,
    autoMatch: 0.8,
    aiReviewUpperBound: 0.8,
    closeCandidateGap: 0.1,
    weakVendor: 0.3,
    weakAmount: 0.3,
    autoMatchComponentFloor: 0.65,
    groupVendorFloor: 0.55,
    partialVendorFloor: 0.5,
    partialAmountFloor: 0.3,
    materialResidualRatio: 0.1,
  },
  vendor: {
    lexicalWeight: 0.7,
    supportingWeight: 0.3,
  },
  memo: {
    conceptWeight: 0.7,
    qualifierWeight: 0.3,
    conceptFloor: 0.5,
    qualifierNeutral: 0.5,
    qualifierAgreement: 1,
    qualifierConflict: 0.2,
  },
  amount: {
    decay: 5,
    directReliability: 1,
    explicitGroupReliability: 1,
    partialBundleReliability: 0.85,
  },
  date: {
    serviceWeight: 0.8,
    postingWeight: 0.2,
    tiers: {
      exact: 1,
      partial: 0.75,
      unavailable: 0.5,
      adjacent: 0.4,
      conflict: 0,
    },
    postingWindowDays: {
      onTime: 45,
      late: 90,
      earlyToleranceDays: 15,
    },
    postingScores: {
      onTime: 1,
      late: 0.5,
      stale: 0,
    },
  },
  glAccount: {
    tiers: {
      strong: 1,
      supported: 0.7,
      neutral: 0.5,
      conflict: 0,
    },
    strongHitCount: 2,
  },
  penalties: {
    periodConflict: 0.2,
    unresolvedResidual: 0.1,
  },
  caps: {
    periodConflict: 0.59,
    unresolvedResidual: 0.79,
    weakVendor: 0.4,
    weakAmount: 0.55,
    belowAutoMatchComponents: 0.79,
  },
  confidenceBands: [
    { minimum: 0.9, label: "Confirmed" },
    { minimum: 0.8, label: "Strong" },
    { minimum: 0.65, label: "Probable" },
    { minimum: 0, label: "Weak" },
  ],
  maxGroupSize: 3,
  maxGroupCandidatePool: 10,
  legalSuffixes: [
    "llc",
    "inc",
    "incorporated",
    "ltd",
    "limited",
    "corp",
    "corporation",
    "plc",
    "llp",
  ],
  abbreviationAliases: {
    ins: "insurance",
    mgmt: "management",
    svc: "service",
    svcs: "service",
    prof: "professional",
    subs: "subscription",
  },
  aggregationTerms: [
    "bundle",
    "combined",
    "consolidated",
    "multiple",
    "plus",
    "quarterly",
    "spanning",
  ],
  lineItemTerms: ["hour", "overage", "retainer"],
  stopWords: [
    "a",
    "an",
    "and",
    "based",
    "for",
    "from",
    "in",
    "invoice",
    "of",
    "on",
    "per",
    "the",
    "to",
    "with",
  ],
  glGlossary: {
    "6100": [
      "cloud",
      "compute",
      "hosting",
      "infrastructure",
      "storage",
      "usage",
    ],
    "6200": [
      "license",
      "prorated",
      "renewal",
      "saas",
      "seat",
      "software",
      "subscription",
    ],
    "6300": [
      "advisory",
      "consulting",
      "hour",
      "overage",
      "professional",
      "retainer",
    ],
    "6400": [
      "broker",
      "coverage",
      "insurance",
      "liability",
      "policy",
      "premium",
      "property",
    ],
    "6500": [
      "facilities",
      "facility",
      "janitorial",
      "maintenance",
      "office",
      "rent",
    ],
    "6600": ["carrier", "delivery", "freight", "logistics", "shipping"],
  },
  openRouter: {
    endpoint: "https://openrouter.ai/api/v1/chat/completions",
    model: "google/gemini-3.1-pro-preview",
    timeoutMs: 30_000,
    maximumAdjustment: 0.05,
    maxOutputTokens: 2000,
    reasoningEffort: "low",
    concurrency: 4,
    maxRetries: 2,
    retryBaseDelayMs: 500,
  },
} as const;
